config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'pages#home'

  get 'intro' => 'pages#intro'

  get 'events/:id/unattend' => 'events#unattend'
  get 'events/:id/cancel' => 'events#cancel'
  get 'events/:id/attend' => 'events#attend'

  resources :users
  resources :events
  resources :listings

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :listings

  has_many :events_participants, foreign_key: :participant_id
  has_many :events_hosts, foreign_key: :host_id

  has_many :events, through: :events_participants
  has_many :hosted_events, through: :events_hosts, source: :event

  geocoded_by :address

  unless Rails.env.test?
    after_validation :geocode, if: :address_changed?
  end

  validates :first_name, presence: true, length: {in: 2..40}
  validates :last_name, presence: true, length: {in: 2..40}

  def address
    "#{self.address_line_1}, #{self.city}, #{self.zipcode}"
  end

  def address_changed?
    if self.address_line_1 && self.city && self.zipcode
      (self.address_line_1_changed? || self.city_changed? || self.zipcode_changed?)
    else
      false
    end
  end

  def coordinates
    [self.latitude.to_f, self.longitude.to_f]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to current_user
  end

  def show
    @listing = Listing.new
    @user = User.find_by(id: params[:id])

    @events = @user.events
    @hosted_events = @user.hosted_events
    @items = Item.all
    @listings = @user.listings
  end

  def create
    if User.find_by(id: params[:id])
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def update
    User.update(params[:id], update_params)
    redirect_to current_user
  end

  private
  def update_params
    params.require(:user).permit(:first_name, :last_name, :username, :email,
                                 :address_line_1, :city, :state, :zipcode, :about, :img, :phone,
                                 :private_contact, :password, :password_confirmation)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_edit.html.haml
#myEditprofile.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'myModalLabel', :role => 'dialog', :tabindex => '-1'}
  .modal-dialog
    .modal-content.text-left
      .modal-header
        %button.close{'data-dismiss' => 'modal', :type => 'button'}
          %span{'aria-hidden' => 'true'} &times;
          %span.sr-only Close
        %h2#myModalLabel.modal-title.bold.c-c4.modalextra EDIT PROFILE
      .modal-body
        = simple_form_for @user do |f|
          = f.input :first_name, class: 'form-control'
          = f.input :last_name, class: 'form-control'
          = f.input :email, class: 'form-control'
          = f.input :private_contact
          (keep my email address private)
          = f.input:address_line_1, class: 'form-control'
          = f.input :city, class: 'form-control'
          = f.input :state, class: 'form-control'
          = f.input :zipcode, class: 'form-control'
          = f.input :about, class: 'form-control'
          = f.submit 'Save changes', class: 'actions m-tb'

app/views/users/_events.html.haml
%li.exchange
  %h3= events.title
  %p
    = events.address_line_1
    = events.city
    = events.zipcode
    %br
    = events.description
  - if user_signed_in? && current_user.id == @user.id
    %p.small.bold.text-right
      = link_to('Unattend', '/events/'+events.id.to_s+'/unattend')

app/views/users/_hosting.html.haml
%li.exchange
  %h3= hosting.title
  %p= hosting.address_line_1
  %p= hosting.city
  %p= hosting.zipcode 
  %p= hosting.description
  %strong
   - if user_signed_in? && current_user.id == @user.id
    = link_to 'Cancel event', "/events/#{hosting.id.to_s}/cancel" |
    = link_to 'Edit event', edit_event_path(hosting)

app/views/users/_listing.html.haml
.listing.col-sm-4.row.m-tb
  .listing-front.col-sm-12 
    .bg-c1.p-tb
      .type-icon.bg-c1-light.abs
        %p= image_tag listing.item.category, alt: 'item-category', class: ''
        #heart      
      .row
        .col-xs-12
          = image_tag listing.image, alt: 'listing-image', class: 'listing-img bg-c3 '
        .col-xs-12
          %h3=listing.title
          %p=listing.description
          %p= "Quantity: #{listing.quantity}"
        - if user_signed_in? && current_user.id == @user.id 
          %br
          %br         
          .button.inl
            = link_to('Edit me', edit_listing_path(listing))
          .button.inl
            = link_to('Delete', listing_path(listing), method: :delete)

app/views/users/show.html.haml
/ LEFT SIDE
%section.user.col-md-3.bg-c2.text-center
  .bg-w
    .user-info
      = image_tag @user.img, alt: 'user-img', class: 'user-img bg-c3'
      %h2= @user.first_name
      %p= @user.about
    .text-center
      - if @user.private_contact == true ||  current_user.id == @user.id
        %a{:href => "mailto:#{@user.email} "}
          %i.fa.fa-envelope-o.fa-3x
        %br
          %br
            %br
      - if user_signed_in? && current_user.id == @user.id
        %div
          %a#js-edit.button{'data-target' => '#myEditprofile', 'data-toggle' => 'modal', :href => '#'} Edit profile
          %br
            %br
        %br
          = render 'edit'
  / EVENTS I WILL ATTEND
  %div
    %h3.bold Exchange's i'm attending
    %ul.exchanges.bg-w.p-tb.text-left
      - if @events && !@events.empty?
        = render partial: 'events', collection: @events
      - else
        %p None right now
  / EVENT HOSTING
  %div
    %h3.bold Exchange's i'm hosting
    - if user_signed_in? && current_user.id == @user.id
      %ul.exchanges.bg-w.p-tb.text-left
        - if @hosted_events && !@hosted_events.empty?          
          = render partial: 'hosting', collection: @hosted_events
        - else
          %p None right now
      %br
        .button.mapbutton
          %a{'data-target' => '#myAddEvent', 'data-toggle' => 'modal'} add exchange
        %br
          / Add Exchange Modal
          = render 'pages/add_event'

/ RIGHT SIDE
%section.listings.bg-c.col-md-9
  - if user_signed_in? && current_user.id == @user.id
    %div
      = render 'listings/form'
  %ul.listings
    - if @listings && !@listings.empty?
      = render partial: 'listing', collection: @listings