config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'pages#home'

  get 'intro' => 'pages#intro'

  get 'events/:id/unattend' => 'events#unattend'
  get 'events/:id/cancel' => 'events#cancel'
  get 'events/:id/attend' => 'events#attend'

  resources :users
  resources :events
  resources :listings

end

app/models/event.rb
ZIP_CODE_REG_EX = %r{\d{5}(-\d{4})?}

class Event < ActiveRecord::Base
  attr_accessor :distance, :counter

  geocoded_by :address

  unless Rails.env.test?
    after_validation :geocode, :if => lambda { |obj| obj.address.present? and obj.address_changed? }
  end

  reverse_geocoded_by :latitude, :longitude

  validates :title, presence: true, length: {in: 3..30}
  validates :address_line_1, presence: true, length: {in: 7..70}
  validates :city, presence: true, length: {in: 3..50}
  validates :zipcode, presence: true
  validates :state, presence: true, format: {with: /\A[a-zA-Z]{2}\z/,
                                             message: 'must be a valid two-letter abbreviation'}
  validates :date, presence: true
  validates :description, presence: true, length: {in: 10..300}

  has_many :events_participants
  has_many :events_hosts

  has_many :participants, class_name: 'User', through: :events_participants
  has_many :hosts, class_name: 'User', through: :events_hosts

  delegate :email,
           :to => :events_host,
           :prefix => true

  def address
    "#{self.address_line_1}, #{self.city}, #{self.zipcode}"
  end

  def address_changed?
    self.address_line_1_changed? || self.city_changed? || self.zipcode_changed?
  end

  def coordinates
    [self.latitude.to_f, self.longitude.to_f]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.hosts << current_user
    if @event.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find_by(id: params[:id])
    render 'events/edit'
  end

  def update
    @event = Event.find_by(id: params[:id])

    if @event.update(event_params)
      redirect_to current_user
    else
      render 'events/edit'
    end
  end

  def cancel
    @event = Event.find_by(id: params[:id])
    @event.destroy
    redirect_to current_user
  end

  def attend
    @event = Event.find_by(id: params[:id])
    EventsParticipant.create(event_id: (params[:id]), participant_id:(current_user.id))
    redirect_to current_user
  end

  def unattend
    @event = Event.find_by(id: params[:id])
    @event.participants.delete(current_user)
    redirect_to current_user
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, 
      :image, :address_line_1, :city, :state, :zipcode, 
      :time, :date)
  end

end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_form.html.haml
= simple_form_for(:event, :url => events_path(:event), 
                          defaults: { wrapper_html: { class: 'field modalextra' }}) do |f|
  = f.input :date, :placeholder => 'you need a date'
  = f.input :time, :placeholder => 'e.g. 9am - 1pm'
  = f.input :title, :placeholder => 'give it a title'
  = f.input :description, :placeholder => 'tell us about the event'
  = f.input :address_line_1, :placeholder => 'some street address'
  = f.input :city, :placeholder => 'some city'
  = f.input :zipcode, :placeholder => 'some zip code'
  .modalextra
    = f.button :submit, 'Submit', class: 'button m-tb'

app/views/events/_show.html.haml
%p= "Title: #{object.title}"
%p= "Address: #{object.address}"
%p= "Date: #{object.date}"
%p= "Time: #{object.time}"
%p= "Distance: #{object.distance} Miles"
%br

app/views/events/edit.html.haml
= render 'form'

app/views/events/new.html.haml
= render 'form'