config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'pages#home'

  get 'intro' => 'pages#intro'

  get 'events/:id/unattend' => 'events#unattend'
  get 'events/:id/cancel' => 'events#cancel'
  get 'events/:id/attend' => 'events#attend'

  resources :users
  resources :events
  resources :listings

end

app/views/pages/_add_event.html.haml
#myAddEvent.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'myModalLabel', :role => 'dialog', :tabindex => '-1'}
  .modal-dialog
    .modal-content.text-left
      .modal-header
        %button.close{'data-dismiss' => 'modal', :type => 'button'}
          %span{'aria-hidden' => 'true'} &times;
          %span.sr-only Close
        %h2#myModalLabel.modal-title.bold.c-c4.modalextra ADD EVENT
      .modal-body
        = render 'events/form'

app/views/pages/_edit_event.html.erb
<div class="modal fade" id="myEditEvent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content text-left">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h2 class="modal-title bold c-c4 modalextra" id="myModalLabel">EDIT EVENT</h2>
      </div>
      <div class="modal-body">
        <%= form_for(:event, :url => edit_events_path(:event), class: 'form') do |f| %>
          <div class="field modalextra">
            <%= f.label :date %><br />
            <%= f.date_field :date, autofocus: true, :placeholder => 'you need adate', class: 'form-control'%>
          </div>
          <div class="field modalextra">
            <%= f.label :time %><br />
            <%= f.text_field :time, autofocus: true, :placeholder => 'e.g. 9am - 1pm', class: 'form-control'%>
          </div>
          <div class="field modalextra">
            <%= f.label :title %><br />
            <%= f.text_field :title, autofocus: true, :placeholder => 'give it a title',class: 'form-control' %>
          </div>
          <div class="field modalextra">
            <%= f.label :description %><br />
            <%= f.text_area :description, autofocus: true, :placeholder => 'tell us about the event', class: 'form-control'%>
          </div>
          <div class="field modalextra">
            <%= f.label :address %><br />
            <%= f.text_field :address_line_1, autofocus: true, :placeholder => 'some street address',class: 'form-control' %>
          </div>
          <div class="field modalextra">
            <%= f.label :city %><br />
            <%= f.text_field :city, autofocus: true, :placeholder => 'some city',class: 'form-control' %>
          </div>
          <div class="field modalextra">
            <%= f.label :zipcode %><br />
            <%= f.text_field :zipcode, autofocus: true, :placeholder => 'some zip code', class: 'form-control'%>
          </div>
          <div class="modalextra">
            <%= f.submit 'Submit', class: 'button' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_listing.html.erb
<li class="listing col-sm-6 row m-tb" <%="data-kind= filter-#{l.item.id}"%>>
  <!-- FRONTSIDE -->
  <div class="listing-front col-sm-12">
    <div class="bg-c1 height p-tb">
      <div class="type-icon bg-c1-light abs">
        <p><%= image_tag l.item.category, alt: "item-category", class: "" %></p>
        <!-- <div id="heart"></div> -->
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div>
            <%= image_tag l.image, alt: "listing-image", class: "listing-img bg-c3 " %>
            <a href=<%="/users/#{l.user.id}" %>>
            <%= image_tag l.user_img, alt: "usr-image", class: "user-img-s bg-c4 abs" %>
            </a>
          </div>
        </div>
        <div class="col-xs-12">
          <div>
            <h3><%= l.title %></h3>
            <p><%= l.description %></p>
            <p>Quantity (aprox.): <%= l.quantity %></p>
            <br>
            <a class="bold small flip-to-back" href="">SHOW EXCHANGES</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- BACKSIDE -->
  <div class="listing-events col-sm-12">
    <div class="bg-c4 height overflow p-tb">
      <div class="row">
        <div class="listing-event  c-w  col-xs-12">

              <h3>EXCHANGES:</h3>
              <ul>
                <li class="exchange">
                    <% l.user.hosted_events.each do |e| %>
                    <!-- ADD PIN NUMBER HERE -->
                      <h3> <%= e.title %></h3>
                      <p><%= e.time %> on <%= e.date %></p>
                      <p><%= e.description %></p>
                      <p><%= e.address_line_1 %> <%= e.city %></p>
                      <strong><%= link_to("JOIN", "/events/"+e.id.to_s+"/attend") %></strong>
                    <% end %>
                </li>
              </ul>
              <ul>
                <ul>
                  <li class="exchange">
                    <% l.user.events.each do |e| %>
                    <hr/>
                     <!-- ADD PIN NUMBER HERE -->
                      <h3><%= @counter %> <%= e.title %></h3>
                      <p><%= e.time %> on <%= e.date %></p>
                      <p><%= e.description %></p>
                      <p><%= e.address_line_1 %> <%= e.city %></p>
                      <strong><%= link_to("JOIN", "/events/"+e.id.to_s+"/attend") %><strong>
                    <% end %>
                </li>
                <hr/>
              </ul><br><br>
        </div>
        <div class="listing-event col-xs-12">
          <br>
        <a class="small c-w bold flip-back button" href="">RETURN</a>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/pages/home.html.erb
<section class="page-left map col-md-5 nopadding">

  <!-- MAP -->
  <div class="googlemap" id="multi_markers"></div>
  <% if user_signed_in? %>
    <div class="button-d abs mapbutton">
      <a data-toggle="modal" data-target="#myAddEvent">Add Exchange</a>
    </div>
  <% else %>
    <div class="button-d abs mapbutton">
      <a data-toggle="modal" data-target="#mySignup">Add Exchange</a>
    </div>
  <% end %>
</section>

  <div class="page-right col-md-7 bg-c" >
    <section class="filters">
    <!-- Add Exchange Modal -->
    <%= render 'pages/add_event' %>

      <!-- Type filter -->
      <div class="filter-type row p-tb">
        <div class="col-md-3">
          <h2 class="bold xl">TYPE</h2>
        </div>
        <div class="col-md-9">
          <ul class="type-icons text-center">
          <% @items.each do |item| %>
            <!-- will be created dynamically -->
            <li class="type-icon sort bg-c1-light m-lr inl <%="filter-#{item.id}"%> ">
              <%= image_tag item.category, alt: 'item-category', class: ''%>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
      <!-- Search filed -->
      <div class="filter-search row p-tb">
        <div class="col-md-3">
          <h2 class="bold xl nopadding">SEARCH</h2>
        </div>

         <div class="col-md-7">
          <%= form_tag('/', :method => 'get', id: 'search-form', class: 'form f-width') do %>
            <%= text_field_tag :search, params[:search], placeholder: 'Search Listings', class: 'form-control'%>
          </div>
            <div class="col-md-2">
            <%= submit_tag 'GO', :name => nil, class: 'f-width button-d' %>
          <% end %>
          </div>
      </div>
    </section>

    <section class="listings-section">
        <ul class="listings" id="all-listings ">
          <% if @listings && !@listings.empty? %>
            <%= render(@listings, as: :l, locals: {counter: @counter}) %>            
          <% else %>
          <h2 class="p-tb text-center c-c3 bold xl">
          No results</h2>
          <% end %>
        </ul>
    </section>

  </div> <!-- end of right container-->
<script>
  var handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      zoom:      2,
      center:    new google.maps.LatLng(0, 0)
    },
    internal: {id: 'multi_markers'}},
    function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/pages/intro.html.haml
%section.circle-home
  .container
    .row
      .col-md-6 col-md-offset-3 aloha-editable          
        = link_to '/'
        .circle-logo
          %h1#company
            cultivated commerce
          %p#phone.circle-test text-center %br %br
            the online crop swap