config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'pages#home'

  get 'intro' => 'pages#intro'

  get 'events/:id/unattend' => 'events#unattend'
  get 'events/:id/cancel' => 'events#cancel'
  get 'events/:id/attend' => 'events#attend'

  resources :users
  resources :events
  resources :listings

end

app/views/layouts/_edit_profile.html.erb
<div class="modal fade" id="myEditprofile" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content text-left">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h2 class="modal-title bold c-c4 modalextra" id="myModalLabel">EDIT PROFILE</h2>
      </div>
      <div class="modal-body">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name, class: "form-control"%>
          </div>

          <div class="field">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name, class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, class: "form-control"%>
          </div>
          <br><br>
          <div class="field">
            <%= f.label :keep_my_information_private %><br />
            <%= f.check_box :private_contact  %> (keep my email address private)
          </div> <br><br>

          <div class="field">
            <%= f.label :address %><br />
            <%= f.text_field :address_line_1, class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :city %><br />
            <%= f.text_field :city, class: "form-control" %>
          </div>

           <div class="field">
            <%= f.label :state %><br />
            <%= f.text_field :state, class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :zipcode %><br />
            <%= f.text_field :zipcode, class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :about %><br />
            <%= f.text_area :about, class: "form-control"%>
          </div>

          <div class="actions m-tb">
            <%= f.submit "Save changes", class: "button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.haml
.row.headerline.nopadding
%header.container-fluid.bg-c1
  .row
    .col-md-5
      %a{href: '/'}
        %h1.bold.logo cultivated commerce        
    .col-md-7.pull-right
      %p.navbar-text.pull-right
        - if user_signed_in?
          .userinfo2.pull-right.text-center
            <a href=#{"/users/#{current_user.id}"}>
            \#{image_tag current_user.img, alt: "usr-image", class: "user-img-xs bg-c4"}
          .userinfo1.pull-right.text-center
            <a href=#{"/users/#{current_user.id}"}>
            %strong= current_user.first_name
            %br
              = link_to 'logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'
        - else
          %a{'data-target' => '#mySignup', 'data-toggle' => 'modal', href: ''} Sign up
          |
          %a{'data-target' => '#myLogin', 'data-toggle' => 'modal', href: ''} Login
          = render 'layouts/login'
          = render 'layouts/signup'
        = render 'layouts/messages'

app/views/layouts/_login.html.haml
.modal.fade#myLogin{'tabindex' => '-1', 'role' => 'dialog', 'aria-labelledby' => 'myModalLabel', 'aria-hidden' => 'true' }
  .modal-dialog
    .modal-content
      .modal-header
        %button{ 'type' => 'button', 'class' => 'close', 'data-dismiss' => 'modal' }
          %span{ 'aria-hidden' => 'true' } &times;
          %span.sr-only Close
        %h2.modal-title.bold.c-c4.modalextra.nopadding#myModalLabel LOGIN
      .modal-body
        = simple_form_for(:user, :url => session_path(:user), html: { class: '' }) do |f|
          = f.input :email, input_html: { id: 'js-email-login' }
          - if @validatable
            %em = @minimum_password_length characters minimum
          = f.input :password          
          = f.button :submit, 'Login'

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{'data-dismiss' => 'alert', :href => '#'} ×
    %ul
      %li
        = value

app/views/layouts/_signup.html.haml
#mySignup.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'myModalLabel', :role => 'dialog', :tabindex => '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{'data-dismiss' => 'modal', :type => 'button'}
          %span{'aria-hidden' => 'true'} &times;
          %span.sr-only Close
        %h2#myModalLabel.modal-title.bold.c-c4.modalextra.nopadding Sign up
        %br
        %p{:style => 'c-c4 small;'}
          You need to sign up before adding an exchange
      .modal-body
        = simple_form_for(:user, url: registration_path(:user), html: { class: '' }) do |f|
          = f.input :first_name
          = f.input :last_name
          = f.input :email, placeholder: 'user@domain.com', input_html: { id: 'js-email-signup' }
          = f.input :address_line_1        
          = f.input :city
          = f.input :zipcode
          = f.input :about, as: :text
          - if @validatable
            %em
              (#{@minimum_password_length} characters minimum)
          = f.input :password, input_html: { id: 'js-password-signup' }
          = f.input :password_confirmation, input_html: { id: 'js-password-confirmation-signup' }
          .actions
            = f.button :submit, 'Sign up'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CultivatedCommerce
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js', 'data-turbolinks-track' => true
    = javascript_include_tag '//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry', 'data-turbolinks-track' => true
    = javascript_include_tag '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js', 'data-turbolinks-track' => true
        
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', 
    media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800', media: 'all', 'data-turbolinks-track' => true
    
    = csrf_meta_tags
  %body
    =render 'layouts/header'    
    .container-fluid.nopadding
      .col-md-12.nopadding
        = yield